# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'DoorbiTaxi' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DoorbiTaxi

 pod 'GoogleMaps' 
 pod 'Alamofire'
 pod 'AlamofireImage'
 pod 'SwiftyJSON'
 pod ’GooglePlaces'
 pod 'StarryStars'
 pod 'PayPal-iOS-SDK'
 pod 'ImageSlideshow'
 pod 'IQKeyboardManagerSwift'
 pod 'Google/SignIn'
 pod ’Stripe’
 pod 'Digits'
 pod 'Fabric'
 pod 'Crashlytics'
 pod 'Firebase/Database'
 pod ‘TGPControls’
 pod 'MICountryPicker'

end
